chinese_recovery = "chinese_recovery"
english_recovery = "english_recovery"

Bible_Books_Info = {
    '创' : ['创世记', 'Gen', 'GENESIS'],
    '出' : ['出埃及记', 'Exo', 'EXODUS'],
    '利' : ['利未记', 'Lev','LEVITICUS'],
    '民' : ['民数记', 'Num','NUMBERS'],
    '申' : ['申命记', 'Deut','DEUTERONOMY'],
    '书' : ['约书亚记', 'Josh','JOSHUA'],
    '士' : ['士师记', 'Judg','JUDGES'],
    '得' : ['路得记', 'Ruth','RUTH'],
    '撒上' : ['撒母耳记上', '1 Sam','1 SAMUEL'],
    '撒下' : ['撒母耳记下', '2 Sam','2 SAMUEL'],
    '王上' : ['列王纪上','1 Kings','1 KINGS'],
    '王下' : ['列王纪下','2 Kings','2 KINGS'],
    '代上' : ['历代志上','1 Chron','1 CHRONICLES'],
    '代下' : ['历代志下','2 Chron','2 CHRONICLES'],
    '拉' : ['以斯拉记','Ezra','EZRA'],
    '尼' : ['尼希米记','Neh','NEHEMIAH'],
    '斯' : ['以斯帖记','Esth','ESTHER'],
    '伯' : ['约伯记','Job','JOB'],
    '诗' : ['诗篇','Psa','PSALMS'],
    '箴' : ['箴言','Prov','PROVERBS'],
    '传' : ['传道书','Eccl','ECCLESIASTES'],
    '歌' : ['雅歌','S.S.','SONG OF SONGS'],
    '赛' : ['以赛亚书','Isa','ISAIAH'],
    '耶' : ['耶利米书','Jer','JEREMIAH'],
    '哀' : ['耶利米哀歌','Lam','LAMENTATIONS'],
    '结' : ['以西结书','Ezek','EZEKIEL'],
    '但' : ['但以理书','Dan','DANIEL'],
    '何' : ['何西阿书','Hosea','HOSEA'],
    '珥' : ['约珥书','Joel','JOEL'],
    '摩' : ['阿摩司书','Amos','AMOS'],
    '俄' : ['俄巴底亚书','Obad','OBADIAH'],
    '拿' : ['约拿书','Jonah','JONAH'],
    '弥' : ['弥迦书','Micah','MICAH'],
    '鸿' : ['那鸿书','Nahum','NAHUM'],
    '哈' : ['哈巴谷书','Hab','HABAKKUK'],
    '番' : ['西番雅书','Zeph','ZEPHANIAH'],
    '该' : ['哈该书','Hag','HAGGAI'],
    '亚' : ['撒迦利亚书','Zech','ZECHARIAH'],
    '玛' : ['玛拉基书','Mal','MALACHI'],
    '太' : ['马太福音','Matt','MATTHEW'],
    '可' : ['马可福音','Mark','MARK'],
    '路' : ['路加福音','Luke','LUKE'],
    '约' : ['约翰福音','John','JOHN'],
    '徒' : ['使徒行传','Acts','ACTS'],
    '罗' : ['罗马书','Rom','ROMANS'],
    '林前' : ['哥林多前书','1 Cor','1 CORINTHIANS'],
    '林后' : ['哥林多后书','2 Cor','2 CORINTHIANS'],
    '加' : ['加拉太书','Gal','GALATIANS'],
    '弗' : ['以弗所书','Eph','EPHESIANS'],
    '腓' : ['腓立比书','Phil','PHILIPPIANS'],
    '西' : ['歌罗西书','Col','COLOSSIANS'],
    '帖前' : ['帖撒罗尼迦前书','1 Thes','1 THESSALONIANS'],
    '帖后' : ['帖撒罗尼迦后书','2 Thes','2 THESSALONIANS'],
    '提前' : ['提摩太前书','1 Tim','1 TIMOTHY'],
    '提后' : ['提摩太后书','2 Tim','2 TIMOTHY'],
    '多' : ['提多书','Titus','TITUS'],
    '门' : ['腓利门书','Philem','PHILEMON'],
    '来' : ['希伯来书','Heb','HEBREWS'],
    '雅' : ['雅各书','James','JAMES'],
    '彼前' : ['彼得前书','1 Pet','1 PETER'],
    '彼后' : ['彼得后书','2 Pet','2 PETER'],
    '约壹' : ['约翰壹书','1 John','1 JOHN'],
    '约贰' : ['约翰贰书','2 John','2 JOHN'],
    '约叁' : ['约翰叁书','3 John','3 JOHN'],
    '犹' : ['犹大书','Jude','JUDE'],
    '启' : ['启示录','Rev','REVELATION']
}

