chinese_recovery = "chinese_recovery"
english_recovery = "english_recovery"

Book_Version_Recovery = "Recovery"

Bible_Books_Info = {
    '创' : ['创世记', 'Gen', 'GENESIS', 'Pentateuch'],
    '出' : ['出埃及记', 'Exo', 'EXODUS', 'Pentateuch'],
    '利' : ['利未记', 'Lev','LEVITICUS', 'Pentateuch'],
    '民' : ['民数记', 'Num','NUMBERS', 'Pentateuch'],
    '申' : ['申命记', 'Deut','DEUTERONOMY', 'Pentateuch'],
    '书' : ['约书亚记', 'Josh','JOSHUA', 'History'],
    '士' : ['士师记', 'Judg','JUDGES', 'History'],
    '得' : ['路得记', 'Ruth','RUTH', 'History'],
    '撒上' : ['撒母耳记上', '1 Sam','1 SAMUEL', 'History'],
    '撒下' : ['撒母耳记下', '2 Sam','2 SAMUEL', 'History'],
    '王上' : ['列王纪上','1 Kings','1 KINGS', 'History'],
    '王下' : ['列王纪下','2 Kings','2 KINGS', 'History'],
    '代上' : ['历代志上','1 Chron','1 CHRONICLES', 'History'],
    '代下' : ['历代志下','2 Chron','2 CHRONICLES', 'History'],
    '拉' : ['以斯拉记','Ezra','EZRA', 'History'],
    '尼' : ['尼希米记','Neh','NEHEMIAH', 'History'],
    '斯' : ['以斯帖记','Esth','ESTHER', 'History'],
    '伯' : ['约伯记','Job','JOB', 'Poetry'],
    '诗' : ['诗篇','Psa','PSALMS', 'Poetry'],
    '箴' : ['箴言','Prov','PROVERBS', 'Poetry'],
    '传' : ['传道书','Eccl','ECCLESIASTES', 'Poetry'],
    '歌' : ['雅歌','S.S.','SONG OF SONGS', 'Poetry'],
    '赛' : ['以赛亚书','Isa','ISAIAH', 'Prophecy'],
    '耶' : ['耶利米书','Jer','JEREMIAH', 'Prophecy'],
    '哀' : ['耶利米哀歌','Lam','LAMENTATIONS', 'Prophecy'],
    '结' : ['以西结书','Ezek','EZEKIEL', 'Prophecy'],
    '但' : ['但以理书','Dan','DANIEL', 'Prophecy'],
    '何' : ['何西阿书','Hosea','HOSEA', 'Prophecy'],
    '珥' : ['约珥书','Joel','JOEL', 'Prophecy'],
    '摩' : ['阿摩司书','Amos','AMOS', 'Prophecy'],
    '俄' : ['俄巴底亚书','Obad','OBADIAH', 'Prophecy'],
    '拿' : ['约拿书','Jonah','JONAH', 'Prophecy'],
    '弥' : ['弥迦书','Micah','MICAH', 'Prophecy'],
    '鸿' : ['那鸿书','Nahum','NAHUM', 'Prophecy'],
    '哈' : ['哈巴谷书','Hab','HABAKKUK', 'Prophecy'],
    '番' : ['西番雅书','Zeph','ZEPHANIAH', 'Prophecy'],
    '该' : ['哈该书','Hag','HAGGAI', 'Prophecy'],
    '亚' : ['撒迦利亚书','Zech','ZECHARIAH', 'Prophecy'],
    '玛' : ['玛拉基书','Mal','MALACHI', 'Prophecy'],
    '太' : ['马太福音','Matt','MATTHEW', 'Gospels'],
    '可' : ['马可福音','Mark','MARK', 'Gospels'],
    '路' : ['路加福音','Luke','LUKE', 'Gospels'],
    '约' : ['约翰福音','John','JOHN', 'Gospels'],
    '徒' : ['使徒行传','Acts','ACTS', 'Experience'],
    '罗' : ['罗马书','Rom','ROMANS', 'Experience'],
    '林前' : ['哥林多前书','1 Cor','1 CORINTHIANS', 'Experience'],
    '林后' : ['哥林多后书','2 Cor','2 CORINTHIANS', 'Experience'],
    '加' : ['加拉太书','Gal','GALATIANS', 'Experience'],
    '弗' : ['以弗所书','Eph','EPHESIANS', 'Experience'],
    '腓' : ['腓立比书','Phil','PHILIPPIANS', 'Experience'],
    '西' : ['歌罗西书','Col','COLOSSIANS', 'Experience'],
    '帖前' : ['帖撒罗尼迦前书','1 Thes','1 THESSALONIANS', 'Experience'],
    '帖后' : ['帖撒罗尼迦后书','2 Thes','2 THESSALONIANS', 'Experience'],
    '提前' : ['提摩太前书','1 Tim','1 TIMOTHY', 'Experience'],
    '提后' : ['提摩太后书','2 Tim','2 TIMOTHY', 'Experience'],
    '多' : ['提多书','Titus','TITUS', 'Experience'],
    '门' : ['腓利门书','Philem','PHILEMON', 'Experience'],
    '来' : ['希伯来书','Heb','HEBREWS', 'Experience'],
    '雅' : ['雅各书','James','JAMES', 'Experience'],
    '彼前' : ['彼得前书','1 Pet','1 PETER', 'Experience'],
    '彼后' : ['彼得后书','2 Pet','2 PETER', 'Experience'],
    '约壹' : ['约翰壹书','1 John','1 JOHN', 'Experience'],
    '约贰' : ['约翰贰书','2 John','2 JOHN', 'Experience'],
    '约叁' : ['约翰叁书','3 John','3 JOHN', 'Experience'],
    '犹' : ['犹大书','Jude','JUDE', 'Experience'],
    '启' : ['启示录','Rev','REVELATION', 'Prophecy']
}

